/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'statusMsg'
 * message type.
 */

public class statusMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 3;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 139;

    /** Create a new statusMsg of size 3. */
    public statusMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new statusMsg of the given data_length. */
    public statusMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new statusMsg with the given data_length
     * and base offset.
     */
    public statusMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new statusMsg using the given byte array
     * as backing store.
     */
    public statusMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new statusMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public statusMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new statusMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public statusMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    // Message-type-specific:

    /**
     * Return the value (as a int) of the field 'chunkNum'
     */
    public int get_chunkNum() {
        return (int)getUIntBEElement(0, 16);
    }

    /**
     * Return the value (as a short) of the field 'status'
     */
    public short get_status() {
        return (short)getUIntBEElement(16, 8);
    }

    /**
     * Set the value of the field 'status'
     */
    public void set_status(short value) {
        setUIntBEElement(16, 8, value);
    }
}
